# Generated by Django 5.0.4 on 2024-05-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_fruit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
