# Generated by Django 5.0.4 on 2024-05-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='b_title',
            field=models.CharField(default='blog', max_length=100),
        ),
    ]
