# Generated by Django 5.0.4 on 2024-05-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_author_blog_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='auth_name',
            field=models.CharField(default='author', max_length=50, verbose_name='Author Name '),
        ),
        migrations.AlterField(
            model_name='blog',
            name='b_title',
            field=models.CharField(default='blog', max_length=100, verbose_name='Blog Name '),
        ),
    ]
